title: My Blog Title
description: This is where the description of your site will go.
github_username: shahjalaledu
email: your-email@example.com
twitter_username:

# Set this to true to get LaTeX math equation support
use_math: true

google_analytics:

theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false  # <--- FIXED THIS LINE
  syntax_highlighter: rouge
